//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSchedularNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public int EMPLOYEEID { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string GENDER { get; set; }
        public string CATEGORY_NAME { get; set; }
        public string DESIGNATION_NAME { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string EMAIL_ID { get; set; }
        public string UNIT { get; set; }
        public Nullable<double> REPORTING_MANAGER_ID { get; set; }
        public string REPORTING_MANAGER_NAME { get; set; }
        public string REPORTING_MANAGER_EMAILID { get; set; }
        public Nullable<int> DpartMentID { get; set; }
        public string RFID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public string Employee_Contract { get; set; }
        public string EmployeeMode { get; set; }
        public int SNO { get; set; }
    }
}
