//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSchedularNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int id { get; set; }
        public string text { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string SourceId { get; set; }
        public string TargetId { get; set; }
        public string subject { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
        public string Themecolor { get; set; }
        public Nullable<int> empID { get; set; }
        public string empName { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string EventStatus { get; set; }
    }
}
