//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSchedularNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenceHallEntities3 : DbContext
    {
        public ConferenceHallEntities3()
            : base("name=ConferenceHallEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventsData> EventsDatas { get; set; }
        public virtual DbSet<EventsScheduler> EventsSchedulers { get; set; }
        public virtual DbSet<ConferenceRoomMaster> ConferenceRoomMasters { get; set; }
        public virtual DbSet<NewEventsData> NewEventsDatas { get; set; }
        public virtual DbSet<PlantMaster> PlantMasters { get; set; }
        public virtual DbSet<UnitMaster> UnitMasters { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    }
}
