//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSchedularNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster
    {
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
