//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSchedularNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserLoginID { get; set; }
        public Nullable<int> EmployeeUserID { get; set; }
        public string LoginPassword { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> UpdatedDateTime { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string UserType { get; set; }
    }
}
